environment: prod
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
url: "https://celj.github.io"
plugins:
    - jekyll-feed
    - jekyll-katex
    - jekyll-scholar
    - jekyll-sitemap
katex:
    js_path: "assets"
    rendering_options:
        error_color: "#cc0000"
        throw_error: false
