defaults:
    - scope:
          path: "_posts/coursework"
      values:
          type: "coursework"
    - scope:
          path: "_posts/ml_intro"
      values:
          type: "ml_intro"
    - scope:
          path: "_posts/web_dev_basics"
      values:
          type: "web_dev_basics"
environment: prod
future: true
highlighter: rouge
katex:
    js_path: "assets"
    rendering_options:
        error_color: "#cc0000"
        throw_error: false
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-feed
    - jekyll-katex
    - jekyll-scholar
    - jekyll-sitemap
url: "https://celj.github.io"
